import 'package:flutter/material.dart';

class HeightBox {
  HeightBox._();

  static SizedBox size1 = const SizedBox(height: 1);
  static SizedBox size2 = const SizedBox(height: 2);
  static SizedBox size3 = const SizedBox(height: 3);
  static SizedBox size4 = const SizedBox(height: 4);
  static SizedBox size5 = const SizedBox(height: 5);
  static SizedBox size6 = const SizedBox(height: 6);
  static SizedBox size7 = const SizedBox(height: 7);
  static SizedBox size8 = const SizedBox(height: 8);
  static SizedBox size9 = const SizedBox(height: 9);
  static SizedBox size10 = const SizedBox(height: 10);
  static SizedBox size11 = const SizedBox(height: 11);
  static SizedBox size12 = const SizedBox(height: 12);
  static SizedBox size13 = const SizedBox(height: 13);
  static SizedBox size14 = const SizedBox(height: 14);
  static SizedBox size15 = const SizedBox(height: 15);
  static SizedBox size16 = const SizedBox(height: 16);
  static SizedBox size17 = const SizedBox(height: 17);
  static SizedBox size18 = const SizedBox(height: 18);
  static SizedBox size19 = const SizedBox(height: 19);
  static SizedBox size20 = const SizedBox(height: 20);
  static SizedBox size21 = const SizedBox(height: 21);
  static SizedBox size22 = const SizedBox(height: 22);
  static SizedBox size23 = const SizedBox(height: 23);
  static SizedBox size24 = const SizedBox(height: 24);
  static SizedBox size25 = const SizedBox(height: 25);
  static SizedBox size26 = const SizedBox(height: 26);
  static SizedBox size27 = const SizedBox(height: 27);
  static SizedBox size28 = const SizedBox(height: 28);
  static SizedBox size29 = const SizedBox(height: 29);
  static SizedBox size30 = const SizedBox(height: 30);
  static SizedBox size31 = const SizedBox(height: 31);
  static SizedBox size32 = const SizedBox(height: 32);
  static SizedBox size33 = const SizedBox(height: 33);
  static SizedBox size34 = const SizedBox(height: 34);
  static SizedBox size35 = const SizedBox(height: 35);
  static SizedBox size36 = const SizedBox(height: 36);
  static SizedBox size37 = const SizedBox(height: 37);
  static SizedBox size38 = const SizedBox(height: 38);
  static SizedBox size39 = const SizedBox(height: 39);
  static SizedBox size40 = const SizedBox(height: 40);
  static SizedBox size41 = const SizedBox(height: 41);
  static SizedBox size42 = const SizedBox(height: 42);
  static SizedBox size43 = const SizedBox(height: 43);
  static SizedBox size44 = const SizedBox(height: 44);
  static SizedBox size45 = const SizedBox(height: 45);
  static SizedBox size46 = const SizedBox(height: 46);
  static SizedBox size47 = const SizedBox(height: 47);
  static SizedBox size48 = const SizedBox(height: 48);
  static SizedBox size49 = const SizedBox(height: 49);
  static SizedBox size50 = const SizedBox(height: 50);
}

class WidthBox {
  WidthBox._();

  static SizedBox size1 = const SizedBox(width: 1);
  static SizedBox size2 = const SizedBox(width: 2);
  static SizedBox size3 = const SizedBox(width: 3);
  static SizedBox size4 = const SizedBox(width: 4);
  static SizedBox size5 = const SizedBox(width: 5);
  static SizedBox size6 = const SizedBox(width: 6);
  static SizedBox size7 = const SizedBox(width: 7);
  static SizedBox size8 = const SizedBox(width: 8);
  static SizedBox size9 = const SizedBox(width: 9);
  static SizedBox size10 = const SizedBox(width: 10);
  static SizedBox size11 = const SizedBox(width: 11);
  static SizedBox size12 = const SizedBox(width: 12);
  static SizedBox size13 = const SizedBox(width: 13);
  static SizedBox size14 = const SizedBox(width: 14);
  static SizedBox size15 = const SizedBox(width: 15);
  static SizedBox size16 = const SizedBox(width: 16);
  static SizedBox size17 = const SizedBox(width: 17);
  static SizedBox size18 = const SizedBox(width: 18);
  static SizedBox size19 = const SizedBox(width: 19);
  static SizedBox size20 = const SizedBox(width: 20);
  static SizedBox size21 = const SizedBox(width: 21);
  static SizedBox size22 = const SizedBox(width: 22);
  static SizedBox size23 = const SizedBox(width: 23);
  static SizedBox size24 = const SizedBox(width: 24);
  static SizedBox size25 = const SizedBox(width: 25);
  static SizedBox size26 = const SizedBox(width: 26);
  static SizedBox size27 = const SizedBox(width: 27);
  static SizedBox size28 = const SizedBox(width: 28);
  static SizedBox size29 = const SizedBox(width: 29);
  static SizedBox size30 = const SizedBox(width: 30);
  static SizedBox size31 = const SizedBox(width: 31);
  static SizedBox size32 = const SizedBox(width: 32);
  static SizedBox size33 = const SizedBox(width: 33);
  static SizedBox size34 = const SizedBox(width: 34);
  static SizedBox size35 = const SizedBox(width: 35);
  static SizedBox size36 = const SizedBox(width: 36);
  static SizedBox size37 = const SizedBox(width: 37);
  static SizedBox size38 = const SizedBox(width: 38);
  static SizedBox size39 = const SizedBox(width: 39);
  static SizedBox size40 = const SizedBox(width: 40);
  static SizedBox size41 = const SizedBox(width: 41);
  static SizedBox size42 = const SizedBox(width: 42);
  static SizedBox size43 = const SizedBox(width: 43);
  static SizedBox size44 = const SizedBox(width: 44);
  static SizedBox size45 = const SizedBox(width: 45);
  static SizedBox size46 = const SizedBox(width: 46);
  static SizedBox size47 = const SizedBox(width: 47);
  static SizedBox size48 = const SizedBox(width: 48);
  static SizedBox size49 = const SizedBox(width: 49);
  static SizedBox size50 = const SizedBox(width: 50);
}
